version: '3.3'

services:

  apache:
    # image: 'php:7.4-apache'
    build:
      context: ./DockerFiles
      dockerfile: php.dockerfile
    container_name: php
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql
    container_name: mysql-srv
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-srv
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
